# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        MainWindow.setBaseSize(QtCore.QSize(500, 600))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_grade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_grade.setGeometry(QtCore.QRect(310, 140, 110, 20))
        self.input_grade.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.input_grade.setText("")
        self.input_grade.setObjectName("input_grade")
        self.input_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(70, 140, 110, 20))
        self.input_name.setObjectName("input_name")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(160, 40, 180, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 120, 91, 16))
        self.label_3.setObjectName("label_3")
        self.direction_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.direction_label.setGeometry(QtCore.QRect(60, 90, 391, 20))
        self.direction_label.setObjectName("direction_label")
        self.button_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(190, 170, 113, 32))
        self.button_enter.setObjectName("button_enter")
        self.added_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.added_label.setGeometry(QtCore.QRect(200, 120, 101, 16))
        self.added_label.setObjectName("added_label")
        self.total_count = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_count.setGeometry(QtCore.QRect(230, 140, 31, 16))
        self.total_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_count.setObjectName("total_count")
        self.output = QtWidgets.QLabel(parent=self.centralwidget)
        self.output.setGeometry(QtCore.QRect(50, 260, 401, 291))
        self.output.setText("")
        self.output.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.output.setObjectName("output")
        self.button_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(310, 170, 113, 32))
        self.button_delete.setObjectName("button_delete")
        self.button_done = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_done.setGeometry(QtCore.QRect(70, 170, 113, 32))
        self.button_done.setObjectName("button_done")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(49, 215, 401, 21))
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grade Calculator"))
        self.title.setText(_translate("MainWindow", "Grade Calculator"))
        self.label_2.setText(_translate("MainWindow", "Student Name"))
        self.label_3.setText(_translate("MainWindow", "Student Grade"))
        self.direction_label.setText(
            _translate("MainWindow", "Please input each Student(s) name and grade, then press enter"))
        self.button_enter.setText(_translate("MainWindow", "Enter"))
        self.added_label.setText(_translate("MainWindow", "Students Added"))
        self.total_count.setText(_translate("MainWindow", "0"))
        self.button_delete.setText(_translate("MainWindow", "Delete Prev"))
        self.button_done.setText(_translate("MainWindow", "Done"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
